# Remote state, one state file per environment. This is written out
# explicitly rather than generated by a wrapper tool, since this project
# doesn't depend on Terragrunt or any other Terraform wrapper.

terraform {
  backend "s3" {
    bucket         = "k8s-demo-tfstate-621508399429"
    key            = "k8s-demo-service/dev/terraform.tfstate"
    region         = "ap-southeast-2"
    use_lockfile   = true
    encrypt        = true
    profile        = "dev-full"
  }
}
