# Remote state, one state file per environment. This is written out
# explicitly rather than generated by a wrapper tool, since this project
# doesn't depend on Terragrunt or any other Terraform wrapper.

terraform {
  backend "s3" {
    bucket         = "k8s-demo-tfstate-621508399429"
    key            = "k8s-demo-service/shared/terraform.tfstate"
    region         = "ap-southeast-2"
    use_lockfile   = true
    encrypt        = true
    # Backend blocks can't reference variables (resolved before any var is
    # evaluated), so this has to be a literal, hardcoded to match this
    # environment's provider profile ("shared-full") rather than var.profile.
    profile        = "shared-full"
  }
}
