# Remote state, one state file per environment. This is written out
# explicitly rather than generated by a wrapper tool, since this project
# doesn't depend on Terragrunt or any other Terraform wrapper.
#
# Bootstrap once per AWS account, then uncomment:
#   aws s3api create-bucket --bucket <your-tfstate-bucket> --region ap-southeast-2
#   aws s3api put-bucket-versioning --bucket <your-tfstate-bucket> --versioning-configuration Status=Enabled
#   aws dynamodb create-table --table-name terraform-locks --attribute-definitions AttributeName=LockID,AttributeType=S \
#       --key-schema AttributeName=LockID,KeyType=HASH --billing-mode PAY_PER_REQUEST
#
# terraform {
#   backend "s3" {
#     bucket         = "<your-tfstate-bucket>"
#     key            = "k8s-demo-service/prod/terraform.tfstate"
#     region         = "ap-southeast-2"
#     dynamodb_table = "terraform-locks"
#     encrypt        = true
#   }
# }
